Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Initiate Provisioning ..."

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", bridge: ["en0: Wi-Fi (AirPort)", "wc4: Ethernet Adaptor (wc4)"]

  config.vm.synced_folder "/Users/craigtrim/data/Data", "/data"
  config.vm.provision :shell, path: "scripts/pymongo.sh"
  #config.vm.provision :shell, path: "scripts/vb_provision.sh"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.ssh.insert_key = true

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = "8192"
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.define "pymongo" do |pymongo|
    pymongo.vm.hostname = "pymongo"
    pymongo.vm.network "private_network", ip: "192.168.34.10"
    pymongo.vm.network "forwarded_port", guest: 80, host: 9050, auto_correct: true
  end

end